apiVersion: v1
kind: Namespace
metadata:
  name: simple-web-app
  labels:
    name: simple-web-app
    environment: development
    managed-by: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
  namespace: simple-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
      annotations:
        argocd-image-updater.argoproj.io/image-list: my-image=gcpa2279/simple-web-app
    spec:
      containers:
      - name: simple-web-app
        image: gcpa2279/simple-web-app:latest
      imagePullSecrets:
      - name: private-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  namespace: simple-web-app
  labels:                          # ✅ Fixed indentation
    app: simple-web-app
spec:
  type: LoadBalancer
  ports:  
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: simple-web-app
